version: "3.9"

services:
  web:
    container_name: web_container
    build:
      context: ./.docker/web
    ports:
      - 3000:3000
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
