import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/src/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen my-8 mx-36">
          <div className="sticky h-120 my-8 top-0 w-full">
            <Header />
          </div>
          <div className="flex-grow">
            <div className="container">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
